//! River input-management, libinput-config, and XKB-config client runtime.

const std = @import("std");
const wayland = @import("wayland");

const event_loop = @import("../linux/event_loop.zig");
const policy = @import("river_input_policy.zig");

const linux = std.os.linux;
const wl = wayland.client.wl;
const river = wayland.client.river;

const log = std.log.scoped(.river_input_manager);

const Device = struct {
    runtime: *Runtime,
    id: u32,
    object: *river.InputDeviceV1,
    type: ?policy.DeviceType = null,
    name: ?[]u8 = null,
    libinput: ?*LibinputDevice = null,
    keyboard: ?*Keyboard = null,
    removed: bool = false,
};

const LibinputDevice = struct {
    runtime: *Runtime,
    object: *river.LibinputDeviceV1,
    device: ?*Device = null,
    state: policy.LibinputState = .{},
    removed: bool = false,
};

const Keyboard = struct {
    runtime: *Runtime,
    object: *river.XkbKeyboardV1,
    device: ?*Device = null,
    state: policy.KeyboardState = .{},
    layout_name: ?[]u8 = null,
    removed: bool = false,
};

const Output = struct {
    runtime: *Runtime,
    id: u32,
    registry_name: u32,
    object: *wl.Output,
    name: ?[]u8 = null,
    removed: bool = false,
};

const Keymap = struct {
    runtime: *Runtime,
    object: *river.XkbKeymapV1,
    id: []u8,
    state: policy.KeymapState = .pending,
    error_message: ?[]u8 = null,
};

const AccelConfig = struct {
    runtime: *Runtime,
    object: *river.LibinputAccelConfigV1,
    id: []u8,
    profile: policy.AccelProfile,
    pending_results: usize = 0,
};

const ResultTarget = union(enum) {
    device: u32,
    accel_config: *AccelConfig,
};

const Result = struct {
    runtime: *Runtime,
    object: *river.LibinputResultV1,
    target: ResultTarget,
    operation: policy.Operation,
};

const Runtime = struct {
    allocator: std.mem.Allocator,
    host: *policy.Host,
    display: *wl.Display,
    registry: *wl.Registry,
    input_manager: ?*river.InputManagerV1 = null,
    libinput_config: ?*river.LibinputConfigV1 = null,
    xkb_config: ?*river.XkbConfigV1 = null,
    input_global: ?u32 = null,
    libinput_global: ?u32 = null,
    xkb_global: ?u32 = null,
    devices: std.ArrayList(*Device) = .empty,
    libinput_devices: std.ArrayList(*LibinputDevice) = .empty,
    keyboards: std.ArrayList(*Keyboard) = .empty,
    outputs: std.ArrayList(*Output) = .empty,
    keymaps: std.ArrayList(*Keymap) = .empty,
    accel_configs: std.ArrayList(*AccelConfig) = .empty,
    results: std.ArrayList(*Result) = .empty,
    events: std.ArrayList(policy.Event) = .empty,
    sync_callback: ?*wl.Callback = null,
    next_id: u32 = 1,
    initializing: bool = true,
    stopping: bool = false,
    input_finished: bool = false,
    libinput_finished: bool = false,
    xkb_finished: bool = false,
    fatal: bool = false,

    fn init(self: *Runtime, allocator: std.mem.Allocator, host: *policy.Host) !void {
        const display = try wl.Display.connect(null);
        errdefer display.disconnect();
        const registry = try display.getRegistry();
        errdefer registry.destroy();

        self.* = .{
            .allocator = allocator,
            .host = host,
            .display = display,
            .registry = registry,
        };
        errdefer self.destroyChildren(false);
        errdefer self.events.deinit(self.allocator);
        registry.setListener(*Runtime, registryListener, self);
        try host.bindInvalidator(self, Runtime.invalidate);
        errdefer host.unbindInvalidator();

        // The first roundtrip discovers globals. The second includes all initial
        // events generated by the bind requests made while dispatching the first.
        if (display.roundtrip() != .SUCCESS) return error.RoundtripFailed;
        if (self.input_manager == null) return error.NoRiverInputManager;
        if (self.libinput_config == null) return error.NoRiverLibinputConfig;
        if (self.xkb_config == null) return error.NoRiverXkbConfig;
        if (self.fatal) return error.RiverInputInitializationFailed;
        if (display.roundtrip() != .SUCCESS) return error.RoundtripFailed;
        if (self.fatal) return error.RiverInputInitializationFailed;
        self.initializing = false;
        try self.processUpdate();
    }

    fn deinit(self: *Runtime) void {
        if (self.sync_callback) |callback| callback.destroy();
        const can_destroy_river = self.allFinished();
        self.destroyChildren(can_destroy_river);
        if (can_destroy_river) {
            self.input_manager.?.destroy();
            self.libinput_config.?.destroy();
            self.xkb_config.?.destroy();
        }
        self.registry.destroy();
        self.display.disconnect();
        self.events.deinit(self.allocator);
    }

    fn destroyChildren(self: *Runtime, destroy_proxies: bool) void {
        for (self.results.items) |result| {
            switch (result.target) {
                .accel_config => |config| config.pending_results -= 1,
                .device => {},
            }
            if (destroy_proxies) result.object.destroy();
            self.allocator.destroy(result);
        }
        self.results.deinit(self.allocator);
        for (self.keymaps.items) |keymap| self.destroyKeymap(keymap, destroy_proxies);
        self.keymaps.deinit(self.allocator);
        for (self.accel_configs.items) |config| self.destroyAccelConfig(config, destroy_proxies);
        self.accel_configs.deinit(self.allocator);
        for (self.keyboards.items) |keyboard| self.destroyKeyboard(keyboard, destroy_proxies);
        self.keyboards.deinit(self.allocator);
        for (self.libinput_devices.items) |device| self.destroyLibinputDevice(device, destroy_proxies);
        self.libinput_devices.deinit(self.allocator);
        for (self.devices.items) |device| self.destroyDevice(device, destroy_proxies);
        self.devices.deinit(self.allocator);
        for (self.outputs.items) |output| self.destroyOutput(output, destroy_proxies);
        self.outputs.deinit(self.allocator);
    }

    fn allocateId(self: *Runtime) !u32 {
        if (self.next_id == std.math.maxInt(u32)) return error.RiverObjectIdExhausted;
        const id = self.next_id;
        self.next_id += 1;
        return id;
    }

    fn allFinished(self: *const Runtime) bool {
        return self.input_finished and self.libinput_finished and self.xkb_finished;
    }

    fn shouldStop(self: *const Runtime) bool {
        return self.fatal or (!self.stopping and
            (self.input_finished or self.libinput_finished or self.xkb_finished));
    }

    fn stop(self: *Runtime) void {
        if (self.stopping) return;
        self.stopping = true;
        if (!self.input_finished) self.input_manager.?.stop();
        if (!self.libinput_finished) self.libinput_config.?.stop();
        if (!self.xkb_finished) self.xkb_config.?.stop();
        while (!self.allFinished()) {
            if (self.display.dispatch() != .SUCCESS) return;
        }
    }

    fn invalidate(ctx: *anyopaque) anyerror!void {
        const self: *Runtime = @ptrCast(@alignCast(ctx));
        if (!self.stopping and !self.fatal) try self.scheduleUpdate();
    }

    fn scheduleUpdate(self: *Runtime) !void {
        if (self.initializing or self.stopping or self.sync_callback != null) return;
        const callback = try self.display.sync();
        self.sync_callback = callback;
        callback.setListener(*Runtime, syncListener, self);
    }

    fn recordEvent(self: *Runtime, event: policy.Event) void {
        self.events.append(self.allocator, event) catch {
            self.fatal = true;
            return;
        };
        self.scheduleUpdate() catch {
            self.fatal = true;
        };
    }

    fn recordStateChanged(self: *Runtime, id: u32) void {
        for (self.events.items) |event| switch (event) {
            .state_changed => |existing| if (existing == id) return,
            else => {},
        };
        self.recordEvent(.{ .state_changed = id });
    }

    fn processUpdate(self: *Runtime) !void {
        if (self.fatal or self.stopping) return;
        self.host.refresh() catch |err| {
            // ensureLoaded keeps the previous successfully loaded root committed.
            log.err("failed to refresh River input policy; keeping the previous policy: {}", .{err});
        };

        var arena = std.heap.ArenaAllocator.init(self.allocator);
        defer arena.deinit();
        const allocator = arena.allocator();
        const context = try self.buildContext(allocator);
        const commands = self.host.update(allocator, context) catch |err| {
            log.err("River input callback failed; applying no changes: {}", .{err});
            self.events.clearRetainingCapacity();
            self.sweepRemoved();
            return;
        };
        self.validateCommands(allocator, commands) catch |err| {
            log.err("River input commands are invalid; applying no changes: {}", .{err});
            self.events.clearRetainingCapacity();
            self.sweepRemoved();
            return;
        };
        // Event payloads may borrow keymap/config strings destroyed by commands.
        self.events.clearRetainingCapacity();
        try self.applyCommands(commands);
        self.sweepRemoved();
    }

    fn buildContext(self: *Runtime, allocator: std.mem.Allocator) !policy.Context {
        var device_count: usize = 0;
        for (self.devices.items) |device| if (!device.removed) {
            device_count += 1;
        };
        const devices = try allocator.alloc(policy.Device, device_count);
        var device_index: usize = 0;
        for (self.devices.items) |device| {
            if (device.removed) continue;
            devices[device_index] = .{
                .id = device.id,
                .type = device.type,
                .name = device.name,
                .libinput = if (device.libinput) |value| if (!value.removed) value.state else null else null,
                .keyboard = if (device.keyboard) |value| if (!value.removed) value.state else null else null,
            };
            device_index += 1;
        }

        var output_count: usize = 0;
        for (self.outputs.items) |output| if (!output.removed) {
            output_count += 1;
        };
        const outputs = try allocator.alloc(policy.Output, output_count);
        var output_index: usize = 0;
        for (self.outputs.items) |output| {
            if (output.removed) continue;
            outputs[output_index] = .{
                .id = output.id,
                .registry_name = output.registry_name,
                .name = output.name,
            };
            output_index += 1;
        }

        const keymaps = try allocator.alloc(policy.Keymap, self.keymaps.items.len);
        for (self.keymaps.items, keymaps) |source, *destination| destination.* = .{
            .id = source.id,
            .state = source.state,
            .error_message = source.error_message,
        };
        const accel_configs = try allocator.alloc(policy.AccelConfig, self.accel_configs.items.len);
        for (self.accel_configs.items, accel_configs) |source, *destination| destination.* = .{
            .id = source.id,
            .profile = source.profile,
        };
        return .{
            .devices = devices,
            .outputs = outputs,
            .keymaps = keymaps,
            .accel_configs = accel_configs,
            .events = self.events.items,
            .input_management_version = self.input_manager.?.getVersion(),
            .libinput_config_version = self.libinput_config.?.getVersion(),
            .xkb_config_version = self.xkb_config.?.getVersion(),
        };
    }

    fn validateCommands(self: *Runtime, allocator: std.mem.Allocator, commands: []const policy.Command) !void {
        var keymaps: std.StringHashMapUnmanaged(policy.KeymapState) = .empty;
        defer keymaps.deinit(allocator);
        for (self.keymaps.items) |keymap| try keymaps.put(allocator, keymap.id, keymap.state);
        var configs: std.StringHashMapUnmanaged(usize) = .empty;
        defer configs.deinit(allocator);
        for (self.accel_configs.items) |config| try configs.put(allocator, config.id, config.pending_results);

        for (commands) |command| {
            try validateScalarCommand(command);
            try validateAccelConfigCommand(&configs, allocator, command);
            if (baseDeviceId(command)) |id| _ = try self.requireDevice(id);
            if (keyboardDeviceId(command)) |id| _ = try self.requireKeyboard(id);
            if (libinputDeviceId(command)) |id| _ = try self.requireLibinput(id);
            switch (command) {
                .create_seat => |value| try validateWaylandString(value.name),
                .destroy_seat => |value| try validateWaylandString(value.name),
                .assign_to_seat => |value| {
                    try validateWaylandString(value.name);
                },
                .map_to_output => |value| {
                    if (value.output) |id| _ = try self.requireOutput(id);
                },
                .create_keymap => |value| {
                    try validateIdentifier(value.id);
                    if (std.mem.indexOfScalar(u8, value.text, 0) != null) return error.InvalidKeymapText;
                    if (keymaps.contains(value.id)) return error.DuplicateKeymap;
                    try keymaps.put(allocator, value.id, .pending);
                },
                .destroy_keymap => |value| {
                    if (!keymaps.remove(value.id)) return error.UnknownKeymap;
                },
                .set_keymap => |value| {
                    if ((keymaps.get(value.id) orelse return error.UnknownKeymap) != .ready)
                        return error.KeymapNotReady;
                },
                .set_layout_by_name => |value| {
                    try validateWaylandString(value.name);
                },
                .set_send_events => |value| {
                    if (value.mode > 2) return error.InvalidSendEventsMode;
                },
                else => {},
            }
        }
    }

    fn applyCommands(self: *Runtime, commands: []const policy.Command) !void {
        for (commands) |command| switch (command) {
            .create_seat => |value| {
                const name = try self.allocator.dupeZ(u8, value.name);
                defer self.allocator.free(name);
                self.input_manager.?.createSeat(name);
            },
            .destroy_seat => |value| {
                const name = try self.allocator.dupeZ(u8, value.name);
                defer self.allocator.free(name);
                self.input_manager.?.destroySeat(name);
            },
            .assign_to_seat => |value| {
                const name = try self.allocator.dupeZ(u8, value.name);
                defer self.allocator.free(name);
                self.findDeviceId(value.device).?.object.assignToSeat(name);
            },
            .set_repeat_info => |value| self.findDeviceId(value.device).?.object.setRepeatInfo(value.rate, value.delay),
            .set_scroll_factor => |value| self.findDeviceId(value.device).?.object.setScrollFactor(wl.Fixed.fromDouble(value.factor)),
            .map_to_output => |value| self.findDeviceId(value.device).?.object.mapToOutput(
                if (value.output) |id| self.findOutputId(id).?.object else null,
            ),
            .map_to_rectangle => |value| self.findDeviceId(value.device).?.object.mapToRectangle(
                value.x,
                value.y,
                value.width,
                value.height,
            ),
            .create_keymap => |value| try self.createKeymap(value),
            .destroy_keymap => |value| {
                const index = self.findKeymapIndex(value.id).?;
                const keymap = self.keymaps.orderedRemove(index);
                self.destroyKeymap(keymap, true);
            },
            .set_keymap => |value| self.findDeviceId(value.device).?.keyboard.?.object.setKeymap(self.findKeymap(value.id).?.object),
            .set_layout_by_index => |value| self.findDeviceId(value.device).?.keyboard.?.object.setLayoutByIndex(value.index),
            .set_layout_by_name => |value| {
                const name = try self.allocator.dupeZ(u8, value.name);
                defer self.allocator.free(name);
                self.findDeviceId(value.device).?.keyboard.?.object.setLayoutByName(name);
            },
            .set_capslock => |value| if (value.enabled)
                self.findDeviceId(value.device).?.keyboard.?.object.capslockEnable()
            else
                self.findDeviceId(value.device).?.keyboard.?.object.capslockDisable(),
            .set_numlock => |value| if (value.enabled)
                self.findDeviceId(value.device).?.keyboard.?.object.numlockEnable()
            else
                self.findDeviceId(value.device).?.keyboard.?.object.numlockDisable(),
            .create_accel_config => |value| try self.createAccelConfig(value.id, value.profile),
            .destroy_accel_config => |value| {
                const index = self.findAccelConfigIndex(value.id).?;
                const config = self.accel_configs.orderedRemove(index);
                self.destroyAccelConfig(config, true);
            },
            .set_accel_points => |value| {
                const config = self.findAccelConfig(value.id).?;
                var step = value.step;
                var step_array = waylandArray(f64, std.mem.asBytes(&step));
                var points_array = waylandArray(f64, std.mem.sliceAsBytes(value.points));
                const object = try config.object.setPoints(
                    @enumFromInt(@intFromEnum(value.type)),
                    &step_array,
                    &points_array,
                );
                try self.addResult(object, .{ .accel_config = config }, .set_accel_points);
            },
            .apply_accel_config => |value| {
                const object = try self.findDeviceId(value.device).?.libinput.?.object.applyAccelConfig(
                    self.findAccelConfig(value.id).?.object,
                );
                try self.addResult(object, .{ .device = value.device }, .apply_accel_config);
            },
            .set_send_events => |value| try self.addDeviceResult(value.device, .set_send_events, try self.findDeviceId(value.device).?.libinput.?.object.setSendEvents(@bitCast(value.mode))),
            .set_tap => |value| try self.addDeviceResult(value.device, .set_tap, try self.findDeviceId(value.device).?.libinput.?.object.setTap(enumCast(river.LibinputDeviceV1.TapState, value.state))),
            .set_tap_button_map => |value| try self.addDeviceResult(value.device, .set_tap_button_map, try self.findDeviceId(value.device).?.libinput.?.object.setTapButtonMap(enumCast(river.LibinputDeviceV1.TapButtonMap, value.map))),
            .set_drag => |value| try self.addDeviceResult(value.device, .set_drag, try self.findDeviceId(value.device).?.libinput.?.object.setDrag(enumCast(river.LibinputDeviceV1.DragState, value.state))),
            .set_drag_lock => |value| try self.addDeviceResult(value.device, .set_drag_lock, try self.findDeviceId(value.device).?.libinput.?.object.setDragLock(enumCast(river.LibinputDeviceV1.DragLockState, value.state))),
            .set_three_finger_drag => |value| try self.addDeviceResult(value.device, .set_three_finger_drag, try self.findDeviceId(value.device).?.libinput.?.object.setThreeFingerDrag(enumCast(river.LibinputDeviceV1.ThreeFingerDragState, value.state))),
            .set_calibration_matrix => |value| {
                var matrix = value.matrix;
                var array = waylandArray(f32, std.mem.asBytes(&matrix));
                try self.addDeviceResult(value.device, .set_calibration_matrix, try self.findDeviceId(value.device).?.libinput.?.object.setCalibrationMatrix(&array));
            },
            .set_accel_profile => |value| try self.addDeviceResult(value.device, .set_accel_profile, try self.findDeviceId(value.device).?.libinput.?.object.setAccelProfile(enumCast(river.LibinputDeviceV1.AccelProfile, value.profile))),
            .set_accel_speed => |value| {
                var speed = value.speed;
                var array = waylandArray(f64, std.mem.asBytes(&speed));
                try self.addDeviceResult(value.device, .set_accel_speed, try self.findDeviceId(value.device).?.libinput.?.object.setAccelSpeed(&array));
            },
            .set_natural_scroll => |value| try self.addDeviceResult(value.device, .set_natural_scroll, try self.findDeviceId(value.device).?.libinput.?.object.setNaturalScroll(binaryEnum(river.LibinputDeviceV1.NaturalScrollState, value.enabled))),
            .set_left_handed => |value| try self.addDeviceResult(value.device, .set_left_handed, try self.findDeviceId(value.device).?.libinput.?.object.setLeftHanded(binaryEnum(river.LibinputDeviceV1.LeftHandedState, value.enabled))),
            .set_click_method => |value| try self.addDeviceResult(value.device, .set_click_method, try self.findDeviceId(value.device).?.libinput.?.object.setClickMethod(enumCast(river.LibinputDeviceV1.ClickMethod, value.method))),
            .set_clickfinger_button_map => |value| try self.addDeviceResult(value.device, .set_clickfinger_button_map, try self.findDeviceId(value.device).?.libinput.?.object.setClickfingerButtonMap(enumCast(river.LibinputDeviceV1.ClickfingerButtonMap, value.map))),
            .set_middle_emulation => |value| try self.addDeviceResult(value.device, .set_middle_emulation, try self.findDeviceId(value.device).?.libinput.?.object.setMiddleEmulation(binaryEnum(river.LibinputDeviceV1.MiddleEmulationState, value.enabled))),
            .set_scroll_method => |value| try self.addDeviceResult(value.device, .set_scroll_method, try self.findDeviceId(value.device).?.libinput.?.object.setScrollMethod(enumCast(river.LibinputDeviceV1.ScrollMethod, value.method))),
            .set_scroll_button => |value| try self.addDeviceResult(value.device, .set_scroll_button, try self.findDeviceId(value.device).?.libinput.?.object.setScrollButton(value.button)),
            .set_scroll_button_lock => |value| try self.addDeviceResult(value.device, .set_scroll_button_lock, try self.findDeviceId(value.device).?.libinput.?.object.setScrollButtonLock(binaryEnum(river.LibinputDeviceV1.ScrollButtonLockState, value.enabled))),
            .set_dwt => |value| try self.addDeviceResult(value.device, .set_dwt, try self.findDeviceId(value.device).?.libinput.?.object.setDwt(binaryEnum(river.LibinputDeviceV1.DwtState, value.enabled))),
            .set_dwtp => |value| try self.addDeviceResult(value.device, .set_dwtp, try self.findDeviceId(value.device).?.libinput.?.object.setDwtp(binaryEnum(river.LibinputDeviceV1.DwtpState, value.enabled))),
            .set_rotation => |value| try self.addDeviceResult(value.device, .set_rotation, try self.findDeviceId(value.device).?.libinput.?.object.setRotation(value.angle)),
        };
    }

    fn createKeymap(self: *Runtime, value: anytype) !void {
        const fd = try createSealedKeymapFd(value.text);
        defer _ = linux.close(fd);
        const object = try self.xkb_config.?.createKeymap(fd, switch (value.format) {
            .text_v1 => .text_v1,
            .text_v2 => .text_v2,
        });
        errdefer object.destroy();
        const keymap = try self.allocator.create(Keymap);
        errdefer self.allocator.destroy(keymap);
        const id = try self.allocator.dupe(u8, value.id);
        errdefer self.allocator.free(id);
        keymap.* = .{ .runtime = self, .object = object, .id = id };
        object.setListener(*Keymap, keymapListener, keymap);
        try self.keymaps.append(self.allocator, keymap);
    }

    fn createAccelConfig(self: *Runtime, id_value: []const u8, profile: policy.AccelProfile) !void {
        const object = try self.libinput_config.?.createAccelConfig(enumCast(river.LibinputDeviceV1.AccelProfile, profile));
        errdefer object.destroy();
        const config = try self.allocator.create(AccelConfig);
        errdefer self.allocator.destroy(config);
        const id = try self.allocator.dupe(u8, id_value);
        errdefer self.allocator.free(id);
        config.* = .{ .runtime = self, .object = object, .id = id, .profile = profile };
        try self.accel_configs.append(self.allocator, config);
    }

    fn addDeviceResult(self: *Runtime, device: u32, operation: policy.Operation, object: *river.LibinputResultV1) !void {
        try self.addResult(object, .{ .device = device }, operation);
    }

    fn addResult(self: *Runtime, object: *river.LibinputResultV1, target: ResultTarget, operation: policy.Operation) !void {
        errdefer object.destroy();
        const result = try self.allocator.create(Result);
        errdefer self.allocator.destroy(result);
        result.* = .{ .runtime = self, .object = object, .target = target, .operation = operation };
        switch (target) {
            .accel_config => |config| config.pending_results += 1,
            .device => {},
        }
        errdefer switch (target) {
            .accel_config => |config| config.pending_results -= 1,
            .device => {},
        };
        object.setListener(*Result, resultListener, result);
        try self.results.append(self.allocator, result);
    }

    fn sweepRemoved(self: *Runtime) void {
        var keyboard_index: usize = 0;
        while (keyboard_index < self.keyboards.items.len) {
            const keyboard = self.keyboards.items[keyboard_index];
            if (!keyboard.removed and (keyboard.device == null or !keyboard.device.?.removed)) {
                keyboard_index += 1;
                continue;
            }
            _ = self.keyboards.orderedRemove(keyboard_index);
            if (keyboard.device) |device| if (device.keyboard == keyboard) {
                device.keyboard = null;
            };
            self.destroyKeyboard(keyboard, true);
        }
        var libinput_index: usize = 0;
        while (libinput_index < self.libinput_devices.items.len) {
            const device = self.libinput_devices.items[libinput_index];
            if (!device.removed and (device.device == null or !device.device.?.removed)) {
                libinput_index += 1;
                continue;
            }
            _ = self.libinput_devices.orderedRemove(libinput_index);
            if (device.device) |base| if (base.libinput == device) {
                base.libinput = null;
            };
            self.destroyLibinputDevice(device, true);
        }
        var device_index: usize = 0;
        while (device_index < self.devices.items.len) {
            const device = self.devices.items[device_index];
            if (!device.removed) {
                device_index += 1;
                continue;
            }
            _ = self.devices.orderedRemove(device_index);
            self.destroyDevice(device, true);
        }
        var output_index: usize = 0;
        while (output_index < self.outputs.items.len) {
            const output = self.outputs.items[output_index];
            if (!output.removed) {
                output_index += 1;
                continue;
            }
            _ = self.outputs.orderedRemove(output_index);
            self.destroyOutput(output, true);
        }
    }

    fn destroyDevice(self: *Runtime, device: *Device, destroy_proxy: bool) void {
        if (device.name) |name| self.allocator.free(name);
        if (destroy_proxy) device.object.destroy();
        self.allocator.destroy(device);
    }

    fn destroyLibinputDevice(self: *Runtime, device: *LibinputDevice, destroy_proxy: bool) void {
        if (destroy_proxy) device.object.destroy();
        self.allocator.destroy(device);
    }

    fn destroyKeyboard(self: *Runtime, keyboard: *Keyboard, destroy_proxy: bool) void {
        if (keyboard.layout_name) |name| self.allocator.free(name);
        if (destroy_proxy) keyboard.object.destroy();
        self.allocator.destroy(keyboard);
    }

    fn destroyOutput(self: *Runtime, output: *Output, destroy_proxy: bool) void {
        if (output.name) |name| self.allocator.free(name);
        if (destroy_proxy) {
            if (output.object.getVersion() >= wl.Output.release_since_version)
                output.object.release()
            else
                output.object.destroy();
        }
        self.allocator.destroy(output);
    }

    fn destroyKeymap(self: *Runtime, keymap: *Keymap, destroy_proxy: bool) void {
        if (keymap.error_message) |message| self.allocator.free(message);
        self.allocator.free(keymap.id);
        if (destroy_proxy) keymap.object.destroy();
        self.allocator.destroy(keymap);
    }

    fn destroyAccelConfig(self: *Runtime, config: *AccelConfig, destroy_proxy: bool) void {
        std.debug.assert(config.pending_results == 0 or !destroy_proxy);
        self.allocator.free(config.id);
        if (destroy_proxy) config.object.destroy();
        self.allocator.destroy(config);
    }

    fn requireDevice(self: *Runtime, id: u32) !*Device {
        const device = self.findDeviceId(id) orelse return error.UnknownInputDevice;
        if (device.removed) return error.RemovedInputDevice;
        return device;
    }

    fn requireLibinput(self: *Runtime, id: u32) !*LibinputDevice {
        const device = try self.requireDevice(id);
        const libinput = device.libinput orelse return error.NotLibinputDevice;
        if (libinput.removed) return error.RemovedLibinputDevice;
        return libinput;
    }

    fn requireKeyboard(self: *Runtime, id: u32) !*Keyboard {
        const device = try self.requireDevice(id);
        const keyboard = device.keyboard orelse return error.NotXkbKeyboard;
        if (keyboard.removed) return error.RemovedXkbKeyboard;
        return keyboard;
    }

    fn requireOutput(self: *Runtime, id: u32) !*Output {
        const output = self.findOutputId(id) orelse return error.UnknownOutput;
        if (output.removed) return error.RemovedOutput;
        return output;
    }

    fn findDevice(self: *Runtime, object: *river.InputDeviceV1) ?*Device {
        for (self.devices.items) |device| if (device.object == object) return device;
        return null;
    }

    fn findDeviceId(self: *Runtime, id: u32) ?*Device {
        for (self.devices.items) |device| if (device.id == id) return device;
        return null;
    }

    fn findOutputId(self: *Runtime, id: u32) ?*Output {
        for (self.outputs.items) |output| if (output.id == id) return output;
        return null;
    }

    fn findOutputRegistryName(self: *Runtime, name: u32) ?*Output {
        for (self.outputs.items) |output| if (output.registry_name == name) return output;
        return null;
    }

    fn findKeymap(self: *Runtime, id: []const u8) ?*Keymap {
        for (self.keymaps.items) |keymap| if (std.mem.eql(u8, keymap.id, id)) return keymap;
        return null;
    }

    fn findKeymapIndex(self: *Runtime, id: []const u8) ?usize {
        for (self.keymaps.items, 0..) |keymap, index| if (std.mem.eql(u8, keymap.id, id)) return index;
        return null;
    }

    fn findAccelConfig(self: *Runtime, id: []const u8) ?*AccelConfig {
        for (self.accel_configs.items) |config| if (std.mem.eql(u8, config.id, id)) return config;
        return null;
    }

    fn findAccelConfigIndex(self: *Runtime, id: []const u8) ?usize {
        for (self.accel_configs.items, 0..) |config, index| if (std.mem.eql(u8, config.id, id)) return index;
        return null;
    }

    fn eventLoopPrepare(ctx: *anyopaque) !event_loop.EventLoop.WaylandPrepare {
        const self: *Runtime = @ptrCast(@alignCast(ctx));
        var dispatched_pending = false;
        while (!self.display.prepareRead()) {
            if (self.display.dispatchPending() != .SUCCESS) return error.DispatchFailed;
            dispatched_pending = true;
        }
        const events: u32 = switch (self.display.flush()) {
            .SUCCESS => linux.EPOLL.IN,
            .AGAIN => linux.EPOLL.IN | linux.EPOLL.OUT,
            else => {
                self.display.cancelRead();
                return error.FlushFailed;
            },
        };
        return .{ .events = events, .dispatched_pending = dispatched_pending };
    }

    fn eventLoopFinish(ctx: *anyopaque, events: u32) !bool {
        const self: *Runtime = @ptrCast(@alignCast(ctx));
        if (events & linux.EPOLL.IN != 0) {
            if (self.display.readEvents() != .SUCCESS) return error.ReadEventsFailed;
        } else {
            self.display.cancelRead();
        }
        if (self.display.dispatchPending() != .SUCCESS) return error.DispatchFailed;
        return !self.shouldStop();
    }

    fn registryListener(registry: *wl.Registry, event: wl.Registry.Event, self: *Runtime) void {
        switch (event) {
            .global => |global| {
                const interface = std.mem.span(global.interface);
                if (std.mem.eql(u8, interface, std.mem.span(river.InputManagerV1.interface.name))) {
                    if (self.input_manager != null) return fatal(self);
                    const object = registry.bind(global.name, river.InputManagerV1, @min(global.version, river.InputManagerV1.generated_version)) catch return fatal(self);
                    self.input_manager = object;
                    self.input_global = global.name;
                    object.setListener(*Runtime, inputManagerListener, self);
                } else if (std.mem.eql(u8, interface, std.mem.span(river.LibinputConfigV1.interface.name))) {
                    if (self.libinput_config != null) return fatal(self);
                    const object = registry.bind(global.name, river.LibinputConfigV1, @min(global.version, river.LibinputConfigV1.generated_version)) catch return fatal(self);
                    self.libinput_config = object;
                    self.libinput_global = global.name;
                    object.setListener(*Runtime, libinputConfigListener, self);
                } else if (std.mem.eql(u8, interface, std.mem.span(river.XkbConfigV1.interface.name))) {
                    if (self.xkb_config != null) return fatal(self);
                    const object = registry.bind(global.name, river.XkbConfigV1, @min(global.version, river.XkbConfigV1.generated_version)) catch return fatal(self);
                    self.xkb_config = object;
                    self.xkb_global = global.name;
                    object.setListener(*Runtime, xkbConfigListener, self);
                } else if (std.mem.eql(u8, interface, std.mem.span(wl.Output.interface.name))) {
                    self.addOutput(registry, global.name, global.version) catch return fatal(self);
                }
            },
            .global_remove => |removed| {
                if (self.input_global == removed.name or self.libinput_global == removed.name or self.xkb_global == removed.name)
                    return fatal(self);
                const output = self.findOutputRegistryName(removed.name) orelse return;
                if (output.removed) return;
                output.removed = true;
                self.recordEvent(.{ .output_removed = output.id });
            },
        }
    }

    fn addOutput(self: *Runtime, registry: *wl.Registry, name: u32, version: u32) !void {
        const object = try registry.bind(name, wl.Output, @min(version, wl.Output.generated_version));
        errdefer if (object.getVersion() >= wl.Output.release_since_version) object.release() else object.destroy();
        const output = try self.allocator.create(Output);
        errdefer self.allocator.destroy(output);
        output.* = .{
            .runtime = self,
            .id = try self.allocateId(),
            .registry_name = name,
            .object = object,
        };
        object.setListener(*Output, outputListener, output);
        try self.outputs.append(self.allocator, output);
        self.recordEvent(.{ .output_added = output.id });
    }

    fn inputManagerListener(_: *river.InputManagerV1, event: river.InputManagerV1.Event, self: *Runtime) void {
        switch (event) {
            .finished => self.input_finished = true,
            .input_device => |value| self.addDevice(value.id) catch fatal(self),
        }
    }

    fn addDevice(self: *Runtime, object: *river.InputDeviceV1) !void {
        const device = try self.allocator.create(Device);
        errdefer self.allocator.destroy(device);
        device.* = .{ .runtime = self, .id = try self.allocateId(), .object = object };
        object.setListener(*Device, inputDeviceListener, device);
        try self.devices.append(self.allocator, device);
        self.recordEvent(.{ .device_added = device.id });
    }

    fn libinputConfigListener(_: *river.LibinputConfigV1, event: river.LibinputConfigV1.Event, self: *Runtime) void {
        switch (event) {
            .finished => self.libinput_finished = true,
            .libinput_device => |value| self.addLibinputDevice(value.id) catch fatal(self),
        }
    }

    fn addLibinputDevice(self: *Runtime, object: *river.LibinputDeviceV1) !void {
        const device = try self.allocator.create(LibinputDevice);
        errdefer self.allocator.destroy(device);
        device.* = .{ .runtime = self, .object = object };
        object.setListener(*LibinputDevice, libinputDeviceListener, device);
        try self.libinput_devices.append(self.allocator, device);
    }

    fn xkbConfigListener(_: *river.XkbConfigV1, event: river.XkbConfigV1.Event, self: *Runtime) void {
        switch (event) {
            .finished => self.xkb_finished = true,
            .xkb_keyboard => |value| self.addKeyboard(value.id) catch fatal(self),
        }
    }

    fn addKeyboard(self: *Runtime, object: *river.XkbKeyboardV1) !void {
        const keyboard = try self.allocator.create(Keyboard);
        errdefer self.allocator.destroy(keyboard);
        keyboard.* = .{ .runtime = self, .object = object };
        object.setListener(*Keyboard, keyboardListener, keyboard);
        try self.keyboards.append(self.allocator, keyboard);
    }

    fn inputDeviceListener(_: *river.InputDeviceV1, event: river.InputDeviceV1.Event, device: *Device) void {
        const self = device.runtime;
        switch (event) {
            .removed => {
                if (device.removed) return;
                device.removed = true;
                self.recordEvent(.{ .device_removed = device.id });
            },
            .type => |value| {
                device.type = switch (value.type) {
                    .keyboard => .keyboard,
                    .pointer => .pointer,
                    .touch => .touch,
                    .tablet => .tablet,
                    else => return fatal(self),
                };
                self.recordStateChanged(device.id);
            },
            .name => |value| {
                replaceString(self.allocator, &device.name, value.name) catch return fatal(self);
                self.recordStateChanged(device.id);
            },
        }
    }

    fn outputListener(_: *wl.Output, event: wl.Output.Event, output: *Output) void {
        switch (event) {
            .name => |value| replaceString(output.runtime.allocator, &output.name, value.name) catch fatal(output.runtime),
            .geometry, .mode, .done, .scale, .description => {},
        }
    }

    fn keyboardListener(_: *river.XkbKeyboardV1, event: river.XkbKeyboardV1.Event, keyboard: *Keyboard) void {
        const self = keyboard.runtime;
        switch (event) {
            .removed => {
                keyboard.removed = true;
                if (keyboard.device) |device| self.recordStateChanged(device.id);
            },
            .input_device => |value| {
                const object = value.device orelse return fatal(self);
                const device = self.findDevice(object) orelse return fatal(self);
                if (device.keyboard != null) return fatal(self);
                keyboard.device = device;
                device.keyboard = keyboard;
                self.recordStateChanged(device.id);
            },
            .layout => |value| {
                const device = keyboard.device orelse return fatal(self);
                const replacement = if (value.name) |name|
                    self.allocator.dupe(u8, std.mem.span(name)) catch return fatal(self)
                else
                    null;
                if (keyboard.layout_name) |name| self.allocator.free(name);
                keyboard.layout_name = replacement;
                keyboard.state.layout_index = value.index;
                keyboard.state.layout_name = replacement;
                self.recordStateChanged(device.id);
            },
            .capslock_enabled, .capslock_disabled => {
                const device = keyboard.device orelse return fatal(self);
                keyboard.state.capslock = switch (event) {
                    .capslock_enabled => true,
                    .capslock_disabled => false,
                    else => unreachable,
                };
                self.recordStateChanged(device.id);
            },
            .numlock_enabled, .numlock_disabled => {
                const device = keyboard.device orelse return fatal(self);
                keyboard.state.numlock = switch (event) {
                    .numlock_enabled => true,
                    .numlock_disabled => false,
                    else => unreachable,
                };
                self.recordStateChanged(device.id);
            },
        }
    }

    fn libinputDeviceListener(
        _: *river.LibinputDeviceV1,
        event: river.LibinputDeviceV1.Event,
        libinput: *LibinputDevice,
    ) void {
        const self = libinput.runtime;
        switch (event) {
            .removed => {
                libinput.removed = true;
                if (libinput.device) |device| self.recordStateChanged(device.id);
                return;
            },
            .input_device => |value| {
                const object = value.device orelse return fatal(self);
                const device = self.findDevice(object) orelse return fatal(self);
                if (device.libinput != null) return fatal(self);
                libinput.device = device;
                device.libinput = libinput;
                self.recordStateChanged(device.id);
                return;
            },
            else => {},
        }
        const device = libinput.device orelse return fatal(self);
        const state = &libinput.state;
        switch (event) {
            .removed, .input_device => unreachable,
            .send_events_support => |value| state.send_events.support = @bitCast(value.modes),
            .send_events_default => |value| state.send_events.default = @bitCast(value.mode),
            .send_events_current => |value| state.send_events.current = @bitCast(value.mode),
            .tap_support => |value| state.tap.support = value.finger_count,
            .tap_default => |value| state.tap.default = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .tap_current => |value| state.tap.current = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .tap_button_map_default => |value| state.tap_button_map.default = policyEnum(policy.TapButtonMap, value.button_map) orelse return fatal(self),
            .tap_button_map_current => |value| state.tap_button_map.current = policyEnum(policy.TapButtonMap, value.button_map) orelse return fatal(self),
            .drag_default => |value| state.drag.default = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .drag_current => |value| state.drag.current = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .drag_lock_default => |value| state.drag_lock.default = policyEnum(policy.DragLockState, value.state) orelse return fatal(self),
            .drag_lock_current => |value| state.drag_lock.current = policyEnum(policy.DragLockState, value.state) orelse return fatal(self),
            .three_finger_drag_support => |value| state.three_finger_drag.support = value.finger_count,
            .three_finger_drag_default => |value| state.three_finger_drag.default = policyEnum(policy.ThreeFingerDragState, value.state) orelse return fatal(self),
            .three_finger_drag_current => |value| state.three_finger_drag.current = policyEnum(policy.ThreeFingerDragState, value.state) orelse return fatal(self),
            .calibration_matrix_support => |value| state.calibration_matrix.support = value.supported != 0,
            .calibration_matrix_default => |value| state.calibration_matrix.default = decodeArray([6]f32, value.matrix) orelse return fatal(self),
            .calibration_matrix_current => |value| state.calibration_matrix.current = decodeArray([6]f32, value.matrix) orelse return fatal(self),
            .accel_profiles_support => |value| state.accel_profile.support = @bitCast(value.profiles),
            .accel_profile_default => |value| state.accel_profile.default = policyEnum(policy.AccelProfile, value.profile) orelse return fatal(self),
            .accel_profile_current => |value| state.accel_profile.current = policyEnum(policy.AccelProfile, value.profile) orelse return fatal(self),
            .accel_speed_default => |value| state.accel_speed.default = decodeArray(f64, value.speed) orelse return fatal(self),
            .accel_speed_current => |value| state.accel_speed.current = decodeArray(f64, value.speed) orelse return fatal(self),
            .natural_scroll_support => |value| state.natural_scroll.support = value.supported != 0,
            .natural_scroll_default => |value| state.natural_scroll.default = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .natural_scroll_current => |value| state.natural_scroll.current = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .left_handed_support => |value| state.left_handed.support = value.supported != 0,
            .left_handed_default => |value| state.left_handed.default = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .left_handed_current => |value| state.left_handed.current = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .click_method_support => |value| state.click_method.support = @bitCast(value.methods),
            .click_method_default => |value| state.click_method.default = policyEnum(policy.ClickMethod, value.method) orelse return fatal(self),
            .click_method_current => |value| state.click_method.current = policyEnum(policy.ClickMethod, value.method) orelse return fatal(self),
            .clickfinger_button_map_default => |value| state.clickfinger_button_map.default = policyEnum(policy.TapButtonMap, value.button_map) orelse return fatal(self),
            .clickfinger_button_map_current => |value| state.clickfinger_button_map.current = policyEnum(policy.TapButtonMap, value.button_map) orelse return fatal(self),
            .middle_emulation_support => |value| state.middle_emulation.support = value.supported != 0,
            .middle_emulation_default => |value| state.middle_emulation.default = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .middle_emulation_current => |value| state.middle_emulation.current = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .scroll_method_support => |value| state.scroll_method.support = @bitCast(value.methods),
            .scroll_method_default => |value| state.scroll_method.default = policyEnum(policy.ScrollMethod, value.method) orelse return fatal(self),
            .scroll_method_current => |value| state.scroll_method.current = policyEnum(policy.ScrollMethod, value.method) orelse return fatal(self),
            .scroll_button_default => |value| state.scroll_button.default = value.button,
            .scroll_button_current => |value| state.scroll_button.current = value.button,
            .scroll_button_lock_default => |value| state.scroll_button_lock.default = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .scroll_button_lock_current => |value| state.scroll_button_lock.current = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .dwt_support => |value| state.dwt.support = value.supported != 0,
            .dwt_default => |value| state.dwt.default = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .dwt_current => |value| state.dwt.current = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .dwtp_support => |value| state.dwtp.support = value.supported != 0,
            .dwtp_default => |value| state.dwtp.default = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .dwtp_current => |value| state.dwtp.current = policyEnum(policy.BinaryState, value.state) orelse return fatal(self),
            .rotation_support => |value| state.rotation.support = value.supported != 0,
            .rotation_default => |value| state.rotation.default = value.angle,
            .rotation_current => |value| state.rotation.current = value.angle,
        }
        self.recordStateChanged(device.id);
    }

    fn keymapListener(_: *river.XkbKeymapV1, event: river.XkbKeymapV1.Event, keymap: *Keymap) void {
        switch (event) {
            .success => {
                keymap.state = .ready;
                keymap.runtime.recordEvent(.{ .keymap_ready = keymap.id });
            },
            .failure => |value| {
                replaceString(keymap.runtime.allocator, &keymap.error_message, value.error_msg) catch return fatal(keymap.runtime);
                keymap.state = .failed;
                keymap.runtime.recordEvent(.{ .keymap_failed = .{
                    .id = keymap.id,
                    .error_message = keymap.error_message.?,
                } });
            },
        }
    }

    fn resultListener(_: *river.LibinputResultV1, event: river.LibinputResultV1.Event, result: *Result) void {
        const self = result.runtime;
        const status: policy.ResultStatus = switch (event) {
            .success => .success,
            .unsupported => .unsupported,
            .invalid => .invalid,
        };
        const target: policy.ResultTarget = switch (result.target) {
            .device => |id| .{ .device = id },
            .accel_config => |config| .{ .accel_config = config.id },
        };
        self.recordEvent(.{ .libinput_result = .{
            .target = target,
            .operation = result.operation,
            .status = status,
        } });
        switch (result.target) {
            .accel_config => |config| config.pending_results -= 1,
            .device => {},
        }
        for (self.results.items, 0..) |candidate, index| {
            if (candidate != result) continue;
            _ = self.results.orderedRemove(index);
            break;
        }
        result.object.destroy();
        self.allocator.destroy(result);
    }

    fn syncListener(callback: *wl.Callback, event: wl.Callback.Event, self: *Runtime) void {
        switch (event) {
            .done => {
                if (self.sync_callback == callback) self.sync_callback = null;
                callback.destroy();
                if (self.stopping or self.fatal) return;
                self.processUpdate() catch {
                    self.fatal = true;
                };
            },
        }
    }
};

pub fn run(allocator: std.mem.Allocator, loop: *event_loop.EventLoop, host: *policy.Host) !void {
    var runtime: Runtime = undefined;
    try runtime.init(allocator, host);
    defer runtime.deinit();
    defer host.unbindInvalidator();

    try loop.setWayland(.{
        .fd = runtime.display.getFd(),
        .ctx = &runtime,
        .prepare = Runtime.eventLoopPrepare,
        .finish = Runtime.eventLoopFinish,
    });
    defer loop.clearWayland();
    try loop.run();
    runtime.stop();
    if (runtime.fatal) return error.RiverInputManagerFailed;
    if (!runtime.allFinished()) return error.RiverInputShutdownFailed;
}

pub fn validateScalarCommand(command: policy.Command) !void {
    switch (command) {
        .set_repeat_info => |value| if (value.rate < 0 or value.delay < 0) return error.InvalidRepeatInfo,
        .set_scroll_factor => |value| {
            const maximum = @as(f64, @floatFromInt(std.math.maxInt(i32))) / 256.0;
            if (!std.math.isFinite(value.factor) or value.factor < 0 or value.factor > maximum)
                return error.InvalidScrollFactor;
        },
        .map_to_rectangle => |value| if (value.width < 0 or value.height < 0) return error.InvalidRectangle,
        .set_accel_speed => |value| if (!std.math.isFinite(value.speed) or value.speed < -1 or value.speed > 1)
            return error.InvalidAccelSpeed,
        .set_rotation => |value| if (value.angle >= 360) return error.InvalidRotation,
        .set_accel_points => |value| {
            if (!std.math.isFinite(value.step) or value.step <= 0 or value.points.len == 0)
                return error.InvalidAccelPoints;
            for (value.points) |point| if (!std.math.isFinite(point)) return error.InvalidAccelPoints;
        },
        .set_calibration_matrix => |value| for (value.matrix) |number| if (!std.math.isFinite(number))
            return error.InvalidCalibrationMatrix,
        else => {},
    }
}

fn validateWaylandString(value: []const u8) !void {
    if (std.mem.indexOfScalar(u8, value, 0) != null) return error.InvalidWaylandString;
}

fn validateIdentifier(value: []const u8) !void {
    if (value.len == 0 or std.mem.indexOfScalar(u8, value, 0) != null) return error.InvalidIdentifier;
}

fn validateAccelConfigCommand(
    configs: *std.StringHashMapUnmanaged(usize),
    allocator: std.mem.Allocator,
    command: policy.Command,
) !void {
    switch (command) {
        .create_accel_config => |value| {
            try validateIdentifier(value.id);
            if (configs.contains(value.id)) return error.DuplicateAccelConfig;
            try configs.put(allocator, value.id, 0);
        },
        .destroy_accel_config => |value| {
            if ((configs.get(value.id) orelse return error.UnknownAccelConfig) != 0)
                return error.AccelConfigInUse;
            _ = configs.remove(value.id);
        },
        .set_accel_points => |value| {
            const pending = configs.getPtr(value.id) orelse return error.UnknownAccelConfig;
            pending.* += 1;
        },
        .apply_accel_config => |value| {
            if (!configs.contains(value.id)) return error.UnknownAccelConfig;
        },
        else => {},
    }
}

fn fatal(runtime: *Runtime) void {
    runtime.fatal = true;
}

fn replaceString(allocator: std.mem.Allocator, destination: *?[]u8, source: [*:0]const u8) !void {
    const replacement = try allocator.dupe(u8, std.mem.span(source));
    if (destination.*) |old| allocator.free(old);
    destination.* = replacement;
}

fn policyEnum(comptime T: type, value: anytype) ?T {
    const integer = @intFromEnum(value);
    inline for (@typeInfo(T).@"enum".fields) |field| {
        if (integer == field.value) return @enumFromInt(field.value);
    }
    return null;
}

fn baseDeviceId(command: policy.Command) ?u32 {
    return switch (command) {
        .assign_to_seat => |value| value.device,
        .set_repeat_info => |value| value.device,
        .set_scroll_factor => |value| value.device,
        .map_to_output => |value| value.device,
        .map_to_rectangle => |value| value.device,
        else => null,
    };
}

fn keyboardDeviceId(command: policy.Command) ?u32 {
    return switch (command) {
        .set_keymap => |value| value.device,
        .set_layout_by_index => |value| value.device,
        .set_layout_by_name => |value| value.device,
        .set_capslock => |value| value.device,
        .set_numlock => |value| value.device,
        else => null,
    };
}

fn libinputDeviceId(command: policy.Command) ?u32 {
    return switch (command) {
        .apply_accel_config => |value| value.device,
        .set_send_events => |value| value.device,
        .set_tap => |value| value.device,
        .set_tap_button_map => |value| value.device,
        .set_drag => |value| value.device,
        .set_drag_lock => |value| value.device,
        .set_three_finger_drag => |value| value.device,
        .set_calibration_matrix => |value| value.device,
        .set_accel_profile => |value| value.device,
        .set_accel_speed => |value| value.device,
        .set_natural_scroll => |value| value.device,
        .set_left_handed => |value| value.device,
        .set_click_method => |value| value.device,
        .set_clickfinger_button_map => |value| value.device,
        .set_middle_emulation => |value| value.device,
        .set_scroll_method => |value| value.device,
        .set_scroll_button => |value| value.device,
        .set_scroll_button_lock => |value| value.device,
        .set_dwt => |value| value.device,
        .set_dwtp => |value| value.device,
        .set_rotation => |value| value.device,
        else => null,
    };
}

fn enumCast(comptime T: type, value: anytype) T {
    return @enumFromInt(@intFromEnum(value));
}

fn binaryEnum(comptime T: type, enabled: bool) T {
    return if (enabled) .enabled else .disabled;
}

fn waylandArray(comptime T: type, bytes: []const u8) wl.Array {
    _ = T;
    return .{ .size = bytes.len, .alloc = bytes.len, .data = @constCast(bytes.ptr) };
}

fn decodeArray(comptime T: type, array: *wl.Array) ?T {
    if (array.size != @sizeOf(T) or array.data == null) return null;
    var value: T = undefined;
    const source: [*]const u8 = @ptrCast(array.data.?);
    @memcpy(std.mem.asBytes(&value), source[0..@sizeOf(T)]);
    return value;
}

fn createSealedKeymapFd(text: []const u8) !i32 {
    const fd = try std.posix.memfd_create("keywork-river-keymap", linux.MFD.CLOEXEC | linux.MFD.ALLOW_SEALING);
    errdefer _ = linux.close(fd);
    const length = std.math.add(usize, text.len, 1) catch return error.KeymapTooLarge;
    if (linux.errno(linux.ftruncate(fd, @intCast(length))) != .SUCCESS) return error.KeymapFdFailed;
    try writeAllFd(fd, text);
    try writeAllFd(fd, "\x00");
    const seals = linux.F.SEAL_WRITE | linux.F.SEAL_GROW | linux.F.SEAL_SHRINK | linux.F.SEAL_SEAL;
    const result = linux.fcntl(fd, linux.F.ADD_SEALS, seals);
    if (linux.errno(result) != .SUCCESS) return error.KeymapSealFailed;
    return fd;
}

fn writeAllFd(fd: i32, data: []const u8) !void {
    var written: usize = 0;
    while (written < data.len) {
        const result = linux.write(fd, data.ptr + written, data.len - written);
        switch (linux.errno(result)) {
            .SUCCESS => written += result,
            .INTR => continue,
            else => return error.KeymapWriteFailed,
        }
    }
}

test "scalar validation rejects protocol-fatal values" {
    try std.testing.expectError(error.InvalidRepeatInfo, validateScalarCommand(.{
        .set_repeat_info = .{ .device = 1, .rate = -1, .delay = 0 },
    }));
    try std.testing.expectError(error.InvalidRotation, validateScalarCommand(.{
        .set_rotation = .{ .device = 1, .angle = 360 },
    }));
    try std.testing.expectError(error.InvalidAccelPoints, validateScalarCommand(.{
        .set_accel_points = .{ .id = "a", .type = .motion, .step = 1, .points = &.{} },
    }));
}

test "accel config cannot be destroyed after creating a result in the same batch" {
    const allocator = std.testing.allocator;
    var configs: std.StringHashMapUnmanaged(usize) = .empty;
    defer configs.deinit(allocator);
    try configs.put(allocator, "curve", 0);
    try validateAccelConfigCommand(&configs, allocator, .{ .set_accel_points = .{
        .id = "curve",
        .type = .motion,
        .step = 1,
        .points = &.{1},
    } });
    try std.testing.expectError(error.AccelConfigInUse, validateAccelConfigCommand(
        &configs,
        allocator,
        .{ .destroy_accel_config = .{ .id = "curve" } },
    ));
}
