//! Ordered Unicode 17.0.0 UAX #14 rules.
//!
//! The state-machine design is derived from ezi-code's MIT-licensed UAX #14
//! implementation, itself a rules-based implementation of revision 55.

const std = @import("std");
const uucode = @import("uucode");
const CodePoint = u21;
const LBProp = @TypeOf(uucode.get(.line_break, 0));

fn decode(bytes: []const u8, pos: usize) struct { code_point: u21, len: usize } {
    const len = std.unicode.utf8ByteSequenceLength(bytes[pos]) catch unreachable;
    return .{ .code_point = std.unicode.utf8Decode(bytes[pos..][0..len]) catch unreachable, .len = len };
}

/// Three-way classification of every position returned by
/// `computeLineBoundaries`.
///
/// UAX #14 distinguishes three outcomes at each potential break, but the
/// boundary-test file in the UCD only marks ÷ vs ×, collapsing two of them.
/// Real consumers (text wrapping to a width, paragraph layout) must know which
/// "÷" was a forced newline from the source vs. a place the engine is allowed
/// to wrap, so we surface the distinction here instead of returning a bool.
pub const LineBreakKind = enum {
    /// No break is permitted before this position (UAX #14 "×").
    prohibited,
    /// A break is permitted before this position; the engine may take it to
    /// fit a line but is not required to (UAX #14 "÷" / "direct break").
    /// The vast majority of in-text break opportunities are this kind.
    opportunity,
    /// A break MUST occur before this position (UAX #14 "!"). Generated by
    /// LB4 (after BK), LB5 (after CR not followed by LF, after LF, after NL),
    /// and LB3 (at end of text). Layout engines must always honor these.
    mandatory,
};

/// Resolve UAX #14's "tailoring" requirement before the rule-pair scan: some
/// raw Line_Break property values must be mapped to a "fixed" value before
/// applying the rules (LB1). AI / SG / XX → AL ; CJ → NS ; SA → CM if the
/// codepoint's General_Category is Mn or Mc, else AL.
fn resolveLineBreakProp(p: LBProp, cp: CodePoint) LBProp {
    return switch (p) {
        .ai, .sg, .xx => .al,
        .sa => blk: {
            const gc = uucode.get(.general_category, cp);
            break :blk if (gc == .mark_nonspacing or gc == .mark_spacing_combining) .cm else .al;
        },
        .cj => .ns,
        else => p,
    };
}

/// True if the property is a space character per UAX #14: SP / ZW.
inline fn lbIsSpaceOrZW(p: LBProp) bool {
    return p == .sp or p == .zw;
}

/// U+25CC DOTTED CIRCLE — referenced verbatim by LB28a as a singleton
/// "AK-base" alongside the AK and AS line-break classes. Its own LB property
/// is AL, so the rule has to consult the raw codepoint.
const DOTTED_CIRCLE: CodePoint = 0x25CC;

inline fn isAKBase(class: LBProp, code_point: CodePoint) bool {
    return class == .ak or class == .as or code_point == DOTTED_CIRCLE;
}

/// Wide enough to count as East_Asian for UAX #14 (F | W | H). Inlined per
/// call site so the algorithm doesn't need to cache an EAW array up front.
inline fn isEastAsianWide(code_point: CodePoint) bool {
    const eaw = uucode.get(.east_asian_width, code_point);
    return eaw == .fullwidth or eaw == .wide or eaw == .halfwidth;
}

inline fn isHangulSyllableClass(class: LBProp) bool {
    return switch (class) {
        .jl, .jv, .jt, .h2, .h3 => true,
        else => false,
    };
}

inline fn isHardLineBreaker(class: LBProp) bool {
    // The five classes that LB9 refuses to absorb a following CM/ZWJ into
    // (forcing LB10's "treat remaining CM/ZWJ as AL" instead). Augmented
    // with SP/ZW per LB9's wording: "X is not BK, CR, LF, NL, SP, or ZW".
    return switch (class) {
        .bk, .cr, .lf, .nl, .sp, .zw => true,
        else => false,
    };
}

/// LB25's back-suffix tracker.  `nu_chain` = "NU (SY|IS)*"; `nu_chain_close`
/// adds an optional trailing single CL or CP. Anything else breaks the
/// chain back to `none`. The chain replaces the unbounded tape walk that
/// the batch algorithm used to do.
const LineNumChain = enum { none, nu_chain, nu_chain_close };

inline fn nextLineNumChain(prev: LineNumChain, cur: LBProp) LineNumChain {
    return switch (cur) {
        .nu => .nu_chain,
        .sy, .is => if (prev == .nu_chain) .nu_chain else .none,
        .cl, .cp => if (prev == .nu_chain) .nu_chain_close else .none,
        else => .none,
    };
}

/// The "fresh" set in LB15a's `(sot | BK | CR | LF | NL | OP | QU | GL | SP | ZW)
/// Pi-QU SP* ×` rule.  Used to decide whether a Pi-class QU should arm
/// `lb15a_armed` when it lands on the effective tape.
inline fn isLB15aFreshClass(c: LBProp) bool {
    return switch (c) {
        .bk, .cr, .lf, .nl, .op, .qu, .gl, .sp, .zw => true,
        else => false,
    };
}

inline fn promoteLB10IfCmZwj(class: LBProp) LBProp {
    return if (class == .cm or class == .zwj) LBProp.al else class;
}

/// One element of the up-to-two effective lookaheads passed into
/// `lineStepRules`.  Stored post-LB9 attachment skipping, post-LB10
/// promotion — exactly the form the rule scan would see if it were
/// looking forward in the effective tape.
const LineLookaheadEntry = struct {
    cp: CodePoint,
    raw: LBProp,
    resolved: LBProp,
};

const LineLookaheadPair = struct {
    n1: ?LineLookaheadEntry = null,
    n2: ?LineLookaheadEntry = null,
};

/// Walk a codepoint slice forward starting at `start`, returning the next
/// up-to-two effective entries.  `initial_prev_resolved` is the resolved
/// class of the most recent non-attached entry just before `start`; it
/// seeds the LB9 attachment decision for the very first candidate.
fn lookaheadFromCodePoints(
    code_points: []const CodePoint,
    start: usize,
    initial_prev_resolved: LBProp,
) LineLookaheadPair {
    var prev_res = initial_prev_resolved;
    var result = LineLookaheadPair{};
    var j = start;
    while (j < code_points.len) : (j += 1) {
        const cp = code_points[j];
        const raw = uucode.get(.line_break, cp);
        const res_pre10 = resolveLineBreakProp(raw, cp);
        const cm_or_zwj = (res_pre10 == .cm or res_pre10 == .zwj);
        if (cm_or_zwj and !isHardLineBreaker(prev_res)) continue;
        const res = promoteLB10IfCmZwj(res_pre10);
        if (result.n1 == null) {
            result.n1 = .{ .cp = cp, .raw = raw, .resolved = res };
            prev_res = res;
        } else {
            result.n2 = .{ .cp = cp, .raw = raw, .resolved = res };
            return result;
        }
    }
    return result;
}

/// Byte-stream variant of `lookaheadFromCodePoints`. Walks forward through
/// UTF-8 codepoints (lossy on invalid sequences) and returns the next
/// up-to-two effective entries.
fn lookaheadFromBytes(
    bytes: []const u8,
    start_byte: usize,
    initial_prev_resolved: LBProp,
) LineLookaheadPair {
    var prev_res = initial_prev_resolved;
    var result = LineLookaheadPair{};
    var j = start_byte;
    while (j < bytes.len) {
        const decoded = decode(bytes, j);
        const cp = decoded.code_point;
        const raw = uucode.get(.line_break, cp);
        const res_pre10 = resolveLineBreakProp(raw, cp);
        const cm_or_zwj = (res_pre10 == .cm or res_pre10 == .zwj);
        j += decoded.len;
        if (cm_or_zwj and !isHardLineBreaker(prev_res)) continue;
        const res = promoteLB10IfCmZwj(res_pre10);
        if (result.n1 == null) {
            result.n1 = .{ .cp = cp, .raw = raw, .resolved = res };
            prev_res = res;
        } else {
            result.n2 = .{ .cp = cp, .raw = raw, .resolved = res };
            return result;
        }
    }
    return result;
}

/// Per-cursor state required to evaluate UAX #14 boundary rules
/// incrementally. Construct via `LineStepState.init(code_points[0])`, then
/// feed each subsequent codepoint through `lineStep` (codepoint slice) or
/// `lineStepBytes` (UTF-8 stream). Memory is O(1): the algorithm's
/// "effective tape" is collapsed into a few scalar fields plus targeted
/// flags for the SP-skipping and numeric-chain lookbacks.
pub const LineStepState = struct {
    /// Raw line-break class of the most recent source codepoint (literal,
    /// before LB10 promotion). LB8a needs the literal ZWJ; nothing else
    /// looks at this.
    raw_prev: ?LBProp = null,

    /// Effective class of the most recent non-attached codepoint
    /// (post-LB9 skip, post-LB10 promotion). null only at sot.
    eff_prev: ?LBProp = null,
    /// The codepoint that produced `eff_prev`. Used for EAW / general
    /// category / extended-pictographic re-queries by LB19a, LB30, LB30b.
    eff_prev_cp: CodePoint = 0,

    /// Effective class of the entry before `eff_prev`. null = sot or
    /// immediately after a break (tape reset). LB19a arm 4, LB20a, LB21a,
    /// and LB28a rule 3 read this slot.
    eff_prev_prev: ?LBProp = null,
    eff_prev_prev_cp: CodePoint = 0,

    /// Most recent non-attached non-SP effective class. Equals `eff_prev`
    /// unless `eff_prev` is SP, in which case it points further back to
    /// the entry the SPs trail. Drives LB8 (ZW SP* ÷), LB14 (OP SP* ×),
    /// LB16 ((CL|CP) SP* × NS), and LB17 (B2 SP* × B2). null = no non-SP
    /// effective entry in the current run yet.
    last_nonsp: ?LBProp = null,
    last_nonsp_cp: CodePoint = 0,

    /// LB15a fast path: true iff `last_nonsp` is a Pi-class QU AND what
    /// came before it (the literal eff_prev at the moment we installed
    /// the Pi-QU) was sot OR in `isLB15aFreshClass`. Set at the moment we
    /// open the Pi-QU window; trailing SPs leave it intact; the next
    /// non-SP entry clears or refreshes it. LB15a fires whenever this
    /// is true without any tape walk.
    lb15a_armed: bool = false,

    /// LB25 numeric chain back-suffix. See `LineNumChain`.
    num_chain: LineNumChain = .none,

    /// Parity of the unbroken RI run ending at `eff_prev`: 1 = odd
    /// (i.e. an unpaired RI), 0 = even.
    ri_parity: u1 = 0,

    /// Initialise state from the first codepoint of the input. LB2 marks
    /// the boundary BEFORE position 0 as `.prohibited`; callers should
    /// emit that themselves, then call `lineStep` for positions ≥ 1.
    ///
    /// @stable-since: v0.1.0
    pub fn init(first_cp: CodePoint) LineStepState {
        const raw = uucode.get(.line_break, first_cp);
        const res_pre10 = resolveLineBreakProp(raw, first_cp);
        // An opening CM/ZWJ at sot has no base, so LB9 cannot attach it;
        // LB10 then promotes it to AL.
        const res = promoteLB10IfCmZwj(res_pre10);
        return .{
            .raw_prev = raw,
            .eff_prev = res,
            .eff_prev_cp = first_cp,
            .eff_prev_prev = null,
            .eff_prev_prev_cp = 0,
            .last_nonsp = if (res == .sp) null else res,
            .last_nonsp_cp = if (res == .sp) 0 else first_cp,
            .lb15a_armed = (res == .qu) and
                uucode.get(.general_category, first_cp) == .punctuation_initial_quote,
            .num_chain = if (res == .nu) .nu_chain else .none,
            .ri_parity = if (res == .ri) 1 else 0,
        };
    }
};

/// Result of `lineStep`: the boundary classification before the current code
/// point, paired with the state to carry into the next step.
pub const LineStepDecision = struct {
    kind: LineBreakKind,
    new_state: LineStepState,
};

/// Result of `lineStepBytes`: like `LineStepDecision` but also reports the byte
/// length of the code point that was just consumed, so iterators can advance
/// without re-decoding.
pub const LineStepByteDecision = struct {
    kind: LineBreakKind,
    new_state: LineStepState,
    /// Byte length of the codepoint that was just stepped over.
    consumed: usize,
};

/// Predicate deciding whether `lineStepRules` can possibly consult the forward
/// lookahead for the (prev, cur) pair. Only LB15b, LB15c, LB19a arm 2, LB25,
/// and LB28a rule 4 ever read the lookahead entries; every other step — the
/// overwhelming majority of real text — can skip the decode-and-classify work
/// of `lookaheadFrom*` entirely and pass an empty pair. The set below is the
/// exact union of those rules' trigger conditions, so a `false` here proves the
/// lookahead is never dereferenced downstream.
inline fn lineNeedsLookahead(state: LineStepState, cur_cp: CodePoint, cur_res: LBProp) bool {
    // LB15b (× Pf-QU …) and LB19a arm 2 (× QU ([^EA] | eot)) both gate on cur QU.
    if (cur_res == .qu) return true;
    const prev = state.eff_prev orelse return false;
    // LB15c: SP ÷ IS NU.
    if (prev == .sp and cur_res == .is) return true;
    // LB25 rules 7/8/10/11: (PO | PR) × OP (NU | IS NU).
    if ((prev == .po or prev == .pr) and cur_res == .op) return true;
    // LB28a rule 4: (AK | DC | AS) × (AK | DC | AS) VF.
    if (isAKBase(cur_res, cur_cp) and isAKBase(prev, state.eff_prev_cp)) return true;
    return false;
}

/// Decide the UAX #14 boundary BEFORE `code_points[i]` given state derived
/// from positions 0..i-1, and return the state to use after consuming
/// position `i`. Caller must have invoked `LineStepState.init(code_points[0])`
/// before the first call (with i == 1).
///
/// @stable-since: v0.1.0
pub fn lineStep(state: LineStepState, code_points: []const CodePoint, i: usize) LineStepDecision {
    const cur_cp = code_points[i];
    const cur_raw = uucode.get(.line_break, cur_cp);
    const cur_res_pre10 = resolveLineBreakProp(cur_raw, cur_cp);

    // LB9 attachment: a CM or ZWJ absorbs into the preceding base unless
    // that base is a "hard breaker" (BK CR LF NL SP ZW). At sot there is
    // no base, so attachment is impossible.
    const cm_or_zwj = (cur_res_pre10 == .cm or cur_res_pre10 == .zwj);
    const attached = cm_or_zwj and if (state.eff_prev) |c| !isHardLineBreaker(c) else false;

    if (attached) {
        // LB9-attached marks are invisible: the boundary before them is
        // unconditionally no-break, and only `raw_prev` advances.
        var new_state = state;
        new_state.raw_prev = cur_raw;
        return .{ .kind = .prohibited, .new_state = new_state };
    }

    // LB10: any unattached CM/ZWJ is promoted to AL for the rule scan.
    const cur_res = promoteLB10IfCmZwj(cur_res_pre10);

    const lookahead = if (lineNeedsLookahead(state, cur_cp, cur_res))
        lookaheadFromCodePoints(code_points, i + 1, cur_res)
    else
        LineLookaheadPair{};
    return lineStepRules(state, cur_cp, cur_raw, cur_res, lookahead);
}

/// Byte-stream variant of `lineStep`. Decodes the codepoint at `byte_pos` and
/// returns the boundary decision plus the byte length consumed by the stepped
/// codepoint, so iterators can advance without re-decoding.
///
/// Contract: `bytes` is valid UTF-8 and `byte_pos < bytes.len` is a scalar
/// boundary. The public iterator validates this contract during init.
///
/// @stable-since: v0.1.0
pub fn lineStepBytes(state: LineStepState, bytes: []const u8, byte_pos: usize) LineStepByteDecision {
    const decoded = decode(bytes, byte_pos);
    const cur_cp = decoded.code_point;
    const cur_raw = uucode.get(.line_break, cur_cp);
    const cur_res_pre10 = resolveLineBreakProp(cur_raw, cur_cp);

    const cm_or_zwj = (cur_res_pre10 == .cm or cur_res_pre10 == .zwj);
    const attached = cm_or_zwj and if (state.eff_prev) |c| !isHardLineBreaker(c) else false;

    if (attached) {
        var new_state = state;
        new_state.raw_prev = cur_raw;
        return .{ .kind = .prohibited, .new_state = new_state, .consumed = decoded.len };
    }

    const cur_res = promoteLB10IfCmZwj(cur_res_pre10);
    const lookahead = if (lineNeedsLookahead(state, cur_cp, cur_res))
        lookaheadFromBytes(bytes, byte_pos + decoded.len, cur_res)
    else
        LineLookaheadPair{};
    const decision = lineStepRules(state, cur_cp, cur_raw, cur_res, lookahead);
    return .{ .kind = decision.kind, .new_state = decision.new_state, .consumed = decoded.len };
}

/// Whether the consumed input ends in a hard line break. This distinguishes a
/// source break at end-of-text from LB3's otherwise-mandatory terminal break.
pub fn endsWithHardBreak(state: LineStepState) bool {
    return switch (state.eff_prev.?) {
        .bk, .cr, .lf, .nl => true,
        else => false,
    };
}

/// Shared rule body. Caller has already decided that the current codepoint
/// is NOT LB9-attached and has applied LB10 to produce `cur_res`. The
/// `lookahead` pair gives the next up-to-two effective entries forward.
fn lineStepRules(state: LineStepState, cur_cp: CodePoint, cur_raw: LBProp, cur_res: LBProp, lookahead: LineLookaheadPair) LineStepDecision {
    // After `lineStepInit`, every subsequent step has a non-null eff_prev.
    const prev = state.eff_prev.?;
    const prev_cp = state.eff_prev_cp;

    // ── Hard exits (LB4–LB8a): return immediately, no allow_break needed. ──

    // LB4: BK !
    if (prev == .bk)
        return .{ .kind = .mandatory, .new_state = stateAfterBreak(cur_cp, cur_raw, cur_res) };

    // LB5: CR × LF ; lone CR / LF / NL !
    switch (prev) {
        .cr => return if (cur_res == .lf)
            .{ .kind = .prohibited, .new_state = stateAfterContinue(state, cur_cp, cur_raw, cur_res) }
        else
            .{ .kind = .mandatory, .new_state = stateAfterBreak(cur_cp, cur_raw, cur_res) },
        .lf, .nl => return .{ .kind = .mandatory, .new_state = stateAfterBreak(cur_cp, cur_raw, cur_res) },
        else => {},
    }

    // LB6: × (BK | CR | LF | NL) ; LB7: × SP ; × ZW
    switch (cur_res) {
        .bk, .cr, .lf, .nl, .sp, .zw => return .{ .kind = .prohibited, .new_state = stateAfterContinue(state, cur_cp, cur_raw, cur_res) },
        else => {},
    }

    // LB8: ZW SP* ÷
    if (state.last_nonsp == .zw)
        return .{ .kind = .opportunity, .new_state = stateAfterBreak(cur_cp, cur_raw, cur_res) };

    // LB8a: ZWJ ×
    if (state.raw_prev == .zwj)
        return .{ .kind = .prohibited, .new_state = stateAfterContinue(state, cur_cp, cur_raw, cur_res) };

    // ── LB11–LB31: default is opportunity; × rules suppress. ──

    var allow_break = true;

    // LB15b and LB19 both read the General_Category of a QU `cur`. Resolve it
    // a single time here (only when `cur` is actually QU, so the common
    // non-quote path pays nothing) rather than hitting the table twice.
    const cur_qu_gc: ?@TypeOf(uucode.get(.general_category, cur_cp)) =
        if (cur_res == .qu) uucode.get(.general_category, cur_cp) else null;

    // LB11: × WJ ; WJ ×
    if (cur_res == .wj or prev == .wj) allow_break = false;

    // LB12: GL ×
    if (allow_break and prev == .gl) allow_break = false;

    // LB12a: [^SP BA HY HH] × GL
    if (allow_break and cur_res == .gl) switch (prev) {
        .sp, .ba, .hy, .hh => {},
        else => allow_break = false,
    };

    // LB13: × CL ; × CP ; × EX ; × SY (IS dropped in Unicode 17)
    if (allow_break) switch (cur_res) {
        .cl, .cp, .ex, .sy => allow_break = false,
        else => {},
    };

    // LB14: OP SP* ×
    if (allow_break and state.last_nonsp == .op) allow_break = false;

    // LB15a: Pi-QU SP* × — flag set when Pi-QU became last_nonsp; SPs preserve it.
    if (allow_break and state.lb15a_armed) allow_break = false;

    // LB15b: × Pf-QU (SP | GL | WJ | CL | QU | CP | EX | IS | SY | BK | CR | LF | NL | ZW | eot)
    if (allow_break and cur_res == .qu and
        cur_qu_gc.? == .punctuation_final_quote)
    {
        const next_ok = if (lookahead.n1) |n| switch (n.resolved) {
            .sp, .gl, .wj, .cl, .qu, .cp, .ex, .is, .sy, .bk, .cr, .lf, .nl, .zw => true,
            else => false,
        } else true; // eot
        if (next_ok) allow_break = false;
    }

    // LB15c (Unicode 17): SP ÷ IS NU — forced opportunity; must fire before LB15d's × IS.
    if (allow_break and prev == .sp and cur_res == .is) {
        if (lookahead.n1) |n| {
            if (n.resolved == .nu)
                return .{ .kind = .opportunity, .new_state = stateAfterBreak(cur_cp, cur_raw, cur_res) };
        }
    }

    // LB15d: × IS
    if (allow_break and cur_res == .is) allow_break = false;

    // LB16: (CL | CP) SP* × NS
    if (allow_break and cur_res == .ns) switch (state.last_nonsp orelse .xx) {
        .cl, .cp => allow_break = false,
        else => {},
    };

    // LB17: B2 SP* × B2
    if (allow_break and cur_res == .b2 and state.last_nonsp == .b2) allow_break = false;

    // LB18: SP ÷ — all SP-lookback rules have fired; commit result now.
    if (prev == .sp) return if (allow_break)
        .{ .kind = .opportunity, .new_state = stateAfterBreak(cur_cp, cur_raw, cur_res) }
    else
        .{ .kind = .prohibited, .new_state = stateAfterContinue(state, cur_cp, cur_raw, cur_res) };

    // LB19: × [QU - Pi] ; [QU - Pf] ×
    if (allow_break and cur_res == .qu and
        cur_qu_gc.? != .punctuation_initial_quote)
        allow_break = false;
    if (allow_break and prev == .qu and
        uucode.get(.general_category, prev_cp) != .punctuation_final_quote)
        allow_break = false;

    // LB19a (Unicode 17): EAW-conditioned QU rules.
    //   Arms 1+2: × QU suppressed when either neighbor is non-EA or next is eot.
    //   Arms 3+4: QU × suppressed when either neighbor is non-EA or sot precedes QU.
    if (allow_break and cur_res == .qu) {
        if (!isEastAsianWide(prev_cp)) allow_break = false; // arm 1: [^EA] × QU
        if (allow_break) {
            const next_non_ea = if (lookahead.n1) |n| !isEastAsianWide(n.cp) else true;
            if (next_non_ea) allow_break = false; // arm 2: × QU ([^EA] | eot)
        }
    }
    if (allow_break and prev == .qu) {
        if (!isEastAsianWide(cur_cp)) allow_break = false; // arm 3: QU × [^EA]
        if (allow_break) {
            // arm 4: (sot | [^EA]) QU × — sot counts as non-EA.
            const before_ea = if (state.eff_prev_prev != null)
                isEastAsianWide(state.eff_prev_prev_cp)
            else
                false;
            if (!before_ea) allow_break = false;
        }
    }

    // LB20: ÷ CB ; CB ÷
    if (allow_break and (cur_res == .cb or prev == .cb))
        return .{ .kind = .opportunity, .new_state = stateAfterBreak(cur_cp, cur_raw, cur_res) };

    // LB20a (Unicode 17): (sot | BK | CR | LF | NL | SP | ZW | CB | GL) (HY | HH) × (AL | HL)
    if (allow_break and (cur_res == .al or cur_res == .hl) and (prev == .hy or prev == .hh)) {
        const fresh = if (state.eff_prev_prev) |c| switch (c) {
            .bk, .cr, .lf, .nl, .sp, .zw, .cb, .gl => true,
            else => false,
        } else true; // sot
        if (fresh) allow_break = false;
    }

    // LB21: × BA ; × HH ; × HY ; × NS ; BB ×
    if (allow_break) switch (cur_res) {
        .ba, .hh, .hy, .ns => allow_break = false,
        else => {
            if (prev == .bb) allow_break = false;
        },
    };

    // LB21a: HL (HY | HH) × [^HL]
    if (allow_break and cur_res != .hl and
        state.eff_prev_prev == .hl and (prev == .hy or prev == .hh))
        allow_break = false;

    // LB21b: SY × HL
    if (allow_break and prev == .sy and cur_res == .hl) allow_break = false;

    // LB22: × IN
    if (allow_break and cur_res == .in) allow_break = false;

    // LB23–LB30 (pair rules): single switch on prev eliminates repeated prev comparisons.
    // LB25 and LB28a are kept separate — they use opaque matchers, not inline conditions.
    if (allow_break) switch (prev) {
        .al, .hl => switch (cur_res) {
            .nu, // LB23: (AL|HL) × NU
            .al,
            .hl, // LB28: (AL|HL) × (AL|HL)
            .pr,
            .po, // LB24: (AL|HL) × (PR|PO)
            => allow_break = false,
            .op => {
                if (!isEastAsianWide(cur_cp)) allow_break = false;
            }, // LB30: × [OP-EA]
            else => {},
        },
        .nu => switch (cur_res) {
            .al, .hl => allow_break = false, // LB23: NU × (AL|HL)
            .op => {
                if (!isEastAsianWide(cur_cp)) allow_break = false;
            }, // LB30: × [OP-EA]
            else => {},
        },
        .pr => switch (cur_res) {
            .id,
            .eb,
            .em, // LB23a: PR × (ID|EB|EM)
            .al,
            .hl, // LB24: PR × (AL|HL)
            .jl,
            .jv,
            .jt,
            .h2,
            .h3, // LB27: PR × Hangul
            => allow_break = false,
            else => {},
        },
        .po => {
            if (cur_res == .al or cur_res == .hl) allow_break = false;
        }, // LB24: PO × (AL|HL)
        .id, .eb, .em => {
            if (cur_res == .po) allow_break = false;
        }, // LB23a: (ID|EB|EM) × PO
        .cp => {
            if (!isEastAsianWide(prev_cp)) switch (cur_res) { // LB30: [CP-EA] × (AL|HL|NU)
                .al, .hl, .nu => allow_break = false,
                else => {},
            };
        },
        .is => {
            if (cur_res == .al or cur_res == .hl) allow_break = false;
        }, // LB29: IS × (AL|HL)
        .jl => switch (cur_res) {
            .jl, .jv, .h2, .h3 => allow_break = false, // LB26: JL × (JL|JV|H2|H3)
            .po => allow_break = false, // LB27: Hangul × PO
            else => {},
        },
        .jv, .h2 => switch (cur_res) {
            .jv, .jt, .po => allow_break = false, // LB26: (JV|H2) × (JV|JT) ; LB27: × PO
            else => {},
        },
        .jt, .h3 => switch (cur_res) {
            .jt, .po => allow_break = false, // LB26: (JT|H3) × JT ; LB27: × PO
            else => {},
        },
        else => {},
    };

    // LB25: numeric chain — multi-class sequence; see lb25MatchesStream for the case map.
    if (allow_break and lb25MatchesStream(state.num_chain, prev, cur_res, lookahead))
        allow_break = false;

    // LB28a: Brahmic virama/linker sequences; see lb28aMatchesStream.
    if (allow_break and lb28aMatchesStream(
        prev,
        cur_res,
        prev_cp,
        cur_cp,
        state.eff_prev_prev,
        state.eff_prev_prev_cp,
        lookahead,
    )) allow_break = false;

    // LB30a: RI × RI when an odd number of preceding RIs completes a pair.
    if (allow_break and prev == .ri and cur_res == .ri and state.ri_parity == 1)
        allow_break = false;

    // LB30b: EB × EM ; [Extended_Pictographic & gc=Cn] × EM
    if (allow_break and cur_res == .em) switch (prev) {
        .eb => allow_break = false,
        else => {
            if (uucode.get(.is_extended_pictographic, prev_cp) and
                uucode.get(.general_category, prev_cp) == .other_not_assigned)
                allow_break = false;
        },
    };

    return if (allow_break)
        .{ .kind = .opportunity, .new_state = stateAfterBreak(cur_cp, cur_raw, cur_res) }
    else
        .{ .kind = .prohibited, .new_state = stateAfterContinue(state, cur_cp, cur_raw, cur_res) };
}

/// State immediately after a break (opportunity or mandatory). The new
/// "effective tape" starts fresh at `cur`, so every back-pointer becomes
/// either `cur` or null. Note: LB7 routes SP and ZW to `stateAfterContinue`,
/// so by the time this is reached `cur_res` is never SP.
inline fn stateAfterBreak(cur_cp: CodePoint, cur_raw: LBProp, cur_res: LBProp) LineStepState {
    return .{
        .raw_prev = cur_raw,
        .eff_prev = cur_res,
        .eff_prev_cp = cur_cp,
        .eff_prev_prev = null,
        .eff_prev_prev_cp = 0,
        .last_nonsp = if (cur_res == .sp) null else cur_res,
        .last_nonsp_cp = if (cur_res == .sp) 0 else cur_cp,
        // A Pi-QU starting a fresh run satisfies LB15a's "before fresh"
        // clause via sot.
        .lb15a_armed = (cur_res == .qu) and
            uucode.get(.general_category, cur_cp) == .punctuation_initial_quote,
        .num_chain = if (cur_res == .nu) .nu_chain else .none,
        .ri_parity = if (cur_res == .ri) 1 else 0,
    };
}

/// State after a non-break boundary (`.prohibited`). The current codepoint
/// joins the effective tape; SP entries preserve `last_nonsp` and
/// `lb15a_armed` so an arbitrarily long SP run keeps the X-SP* lookbacks
/// intact, while non-SP entries refresh both.
inline fn stateAfterContinue(
    state: LineStepState,
    cur_cp: CodePoint,
    cur_raw: LBProp,
    cur_res: LBProp,
) LineStepState {
    var new = LineStepState{};
    new.raw_prev = cur_raw;
    new.eff_prev = cur_res;
    new.eff_prev_cp = cur_cp;
    new.eff_prev_prev = state.eff_prev;
    new.eff_prev_prev_cp = state.eff_prev_cp;

    if (cur_res == .sp) {
        new.last_nonsp = state.last_nonsp;
        new.last_nonsp_cp = state.last_nonsp_cp;
        new.lb15a_armed = state.lb15a_armed;
    } else {
        new.last_nonsp = cur_res;
        new.last_nonsp_cp = cur_cp;
        const is_pi_qu = (cur_res == .qu) and
            uucode.get(.general_category, cur_cp) == .punctuation_initial_quote;
        const before_fresh = if (state.eff_prev) |c| isLB15aFreshClass(c) else true;
        new.lb15a_armed = is_pi_qu and before_fresh;
    }

    new.num_chain = nextLineNumChain(state.num_chain, cur_res);

    if (cur_res == .ri) {
        // RI run accounting: if the run ending at the previous step was
        // odd (parity == 1) and we did not break (only the case if LB30a
        // fired), this RI pairs up — parity flips to even. Otherwise we
        // start a fresh single RI.
        const prev_is_ri = if (state.eff_prev) |c| c == .ri else false;
        if (prev_is_ri and state.ri_parity == 1) {
            new.ri_parity = 0;
        } else {
            new.ri_parity = 1;
        }
    } else {
        new.ri_parity = 0;
    }

    return new;
}

/// Streaming LB25 check. The fifteen UAX #14 numeric sub-rules collapse
/// into: (1) immediate-previous tests for prev × NU; (2) `num_chain` for
/// "NU (SY|IS)* (CL|CP)? × (PO|PR)" and "NU (SY|IS)* × NU"; (3) up to
/// two-step lookahead for "(PO|PR) × OP (NU | IS NU)".
fn lb25MatchesStream(
    chain: LineNumChain,
    prev: LBProp,
    cur: LBProp,
    lookahead: LineLookaheadPair,
) bool {
    // Rules 9 / 12 / 13 / 14 / 15: × NU.
    if (cur == .nu) {
        switch (prev) {
            .po, .pr, .hy, .is => return true,
            else => {},
        }
        if (chain == .nu_chain) return true; // rule 15
    }

    // Rules 7 / 8 / 10 / 11: (PO | PR) × OP (NU | IS NU).
    if ((prev == .po or prev == .pr) and cur == .op) {
        if (lookahead.n1) |n1| {
            if (n1.resolved == .nu) return true;
            if (n1.resolved == .is) {
                if (lookahead.n2) |n2| {
                    if (n2.resolved == .nu) return true;
                }
            }
        }
    }

    // Rules 1..6: NU (SY | IS)* (CL | CP)? × (PO | PR).
    if (cur == .po or cur == .pr) {
        if (chain == .nu_chain or chain == .nu_chain_close) return true;
    }

    return false;
}

/// Streaming LB28a check (Brahmic letter pairs). Sub-rules 1-3 read back
/// at most two effective entries, all available from state. Sub-rule 4
/// uses one effective lookahead.
fn lb28aMatchesStream(
    prev: LBProp,
    cur: LBProp,
    prev_cp: CodePoint,
    cur_cp: CodePoint,
    back2: ?LBProp,
    back2_cp: CodePoint,
    lookahead: LineLookaheadPair,
) bool {
    const prev_is_ak_base = isAKBase(prev, prev_cp);
    const cur_is_ak_base = isAKBase(cur, cur_cp);

    // Rule 1: AP × (AK | DC | AS).
    if (prev == .ap and cur_is_ak_base) return true;

    // Rule 2: (AK | DC | AS) × (VF | VI).
    if (prev_is_ak_base and (cur == .vf or cur == .vi)) return true;

    // Rule 3: (AK | DC | AS) VI × (AK | DC).
    if (prev == .vi and (cur == .ak or cur_cp == DOTTED_CIRCLE)) {
        if (back2) |b2_class| {
            if (isAKBase(b2_class, back2_cp)) return true;
        }
    }

    // Rule 4: (AK | DC | AS) × (AK | DC | AS) VF — one effective lookahead.
    if (prev_is_ak_base and cur_is_ak_base) {
        if (lookahead.n1) |n1| {
            if (n1.resolved == .vf) return true;
        }
    }

    return false;
}

/// Compute line-break classification for a sequence of code points,
/// implementing the full UAX #14 line-break algorithm (Unicode 17.0,
/// rev 55). `out[i]` describes the boundary BEFORE `code_points[i]`:
/// `.prohibited` (× rules), `.opportunity` (÷ rules), or `.mandatory`
/// (LB4/LB5 forced breaks, and LB3 at end-of-text).
///
///   - `out[0]` is `.prohibited` — LB2 ("never break at start of text");
///     for n == 0 the returned slice is a single `.prohibited`.
///   - `out[n]` is `.mandatory` — LB3 ("always break at end of text").
///
/// The three-way classification is the meaningful return type: layout
/// engines must always honor a mandatory break (a literal newline) while
/// opportunities are merely candidate wrap points. Collapsing the two
/// onto a single boolean loses that distinction.
///
/// Internally this is a thin wrapper around the streaming `lineStep`
/// state machine: the only allocation is the returned boundary array
/// itself; the algorithm's prior workspace (raw/resolved class arrays,
/// LB9 attachment table, effective tape) has been replaced with O(1)
/// state inside `LineStepState`.
///
/// @stable-since: v0.1.0
pub fn computeLineBoundaries(allocator: std.mem.Allocator, code_points: []const CodePoint) ![]LineBreakKind {
    const total = code_points.len;
    const boundaries = try allocator.alloc(LineBreakKind, total + 1);
    errdefer allocator.free(boundaries);

    // LB2: × sot.
    boundaries[0] = .prohibited;
    if (total == 0) return boundaries;
    // LB3: ! eot.
    boundaries[total] = .mandatory;
    if (total == 1) return boundaries;

    var state = LineStepState.init(code_points[0]);
    var i: usize = 1;
    while (i < total) : (i += 1) {
        const decision = lineStep(state, code_points, i);
        boundaries[i] = decision.kind;
        state = decision.new_state;
    }
    return boundaries;
}
