[Icon Theme]
Name=Keywork
Comment=Fluent System Icons packaged for Keywork
Inherits=Adwaita,hicolor
Directories=10x10/fluent,12x12/actions,12x12/devices,12x12/fluent,12x12/status,16x16/actions,16x16/categories,16x16/devices,16x16/fluent,16x16/mimetypes,16x16/places,16x16/status,20x20/actions,20x20/categories,20x20/devices,20x20/fluent,20x20/mimetypes,20x20/places,20x20/status,24x24/actions,24x24/categories,24x24/devices,24x24/fluent,24x24/mimetypes,24x24/places,24x24/status,28x28/actions,28x28/categories,28x28/devices,28x28/fluent,28x28/mimetypes,28x28/places,28x28/status,32x32/actions,32x32/categories,32x32/devices,32x32/fluent,32x32/mimetypes,32x32/places,32x32/status,48x48/actions,48x48/categories,48x48/devices,48x48/fluent,48x48/mimetypes,48x48/places,48x48/status

[10x10/fluent]
Size=10
Type=Fixed

[12x12/actions]
Size=12
Type=Fixed
Context=Actions

[12x12/devices]
Size=12
Type=Fixed
Context=Devices

[12x12/fluent]
Size=12
Type=Fixed

[12x12/status]
Size=12
Type=Fixed
Context=Status

[16x16/actions]
Size=16
Type=Fixed
Context=Actions

[16x16/categories]
Size=16
Type=Fixed
Context=Categories

[16x16/devices]
Size=16
Type=Fixed
Context=Devices

[16x16/fluent]
Size=16
Type=Fixed

[16x16/mimetypes]
Size=16
Type=Fixed
Context=MimeTypes

[16x16/places]
Size=16
Type=Fixed
Context=Places

[16x16/status]
Size=16
Type=Fixed
Context=Status

[20x20/actions]
Size=20
Type=Fixed
Context=Actions

[20x20/categories]
Size=20
Type=Fixed
Context=Categories

[20x20/devices]
Size=20
Type=Fixed
Context=Devices

[20x20/fluent]
Size=20
Type=Fixed

[20x20/mimetypes]
Size=20
Type=Fixed
Context=MimeTypes

[20x20/places]
Size=20
Type=Fixed
Context=Places

[20x20/status]
Size=20
Type=Fixed
Context=Status

[24x24/actions]
Size=24
Type=Fixed
Context=Actions

[24x24/categories]
Size=24
Type=Fixed
Context=Categories

[24x24/devices]
Size=24
Type=Fixed
Context=Devices

[24x24/fluent]
Size=24
Type=Fixed

[24x24/mimetypes]
Size=24
Type=Fixed
Context=MimeTypes

[24x24/places]
Size=24
Type=Fixed
Context=Places

[24x24/status]
Size=24
Type=Fixed
Context=Status

[28x28/actions]
Size=28
Type=Fixed
Context=Actions

[28x28/categories]
Size=28
Type=Fixed
Context=Categories

[28x28/devices]
Size=28
Type=Fixed
Context=Devices

[28x28/fluent]
Size=28
Type=Fixed

[28x28/mimetypes]
Size=28
Type=Fixed
Context=MimeTypes

[28x28/places]
Size=28
Type=Fixed
Context=Places

[28x28/status]
Size=28
Type=Fixed
Context=Status

[32x32/actions]
Size=32
Type=Fixed
Context=Actions

[32x32/categories]
Size=32
Type=Fixed
Context=Categories

[32x32/devices]
Size=32
Type=Fixed
Context=Devices

[32x32/fluent]
Size=32
Type=Fixed

[32x32/mimetypes]
Size=32
Type=Fixed
Context=MimeTypes

[32x32/places]
Size=32
Type=Fixed
Context=Places

[32x32/status]
Size=32
Type=Fixed
Context=Status

[48x48/actions]
Size=48
Type=Fixed
Context=Actions

[48x48/categories]
Size=48
Type=Fixed
Context=Categories

[48x48/devices]
Size=48
Type=Fixed
Context=Devices

[48x48/fluent]
Size=48
Type=Fixed

[48x48/mimetypes]
Size=48
Type=Fixed
Context=MimeTypes

[48x48/places]
Size=48
Type=Fixed
Context=Places

[48x48/status]
Size=48
Type=Fixed
Context=Status
